import mysql.connector
db=mysql.connector.connect(host='localhost',
                           user='root',
                           passwd='2707',
                           database='wealthify')
cur=db.cursor()
company_names = [
    "Reliance Industries",
    "HDFC Bank",
    "Infosys",
    "Adani Ports and Special Economic Zone",
    "Asian Paints",
    "Nestle India",
    "Axis Bank",
    "Bajaj Auto",
    "Bajaj Finance",
    "Kotak Mahindra Bank",
    "Bajaj Finserv",
    "Bharti Airtel",
    "Britannia Industries",
    "Cipla",
    "Coal India",
    "Divi's Laboratories",
    "Dr. Reddy's Laboratories",
    "Eicher Motors",
    "Grasim Industries",
    "HCL Technologies",
    "HDFC Asset Management Company",
    "HDFC Life Insurance Company",
    "Hero MotoCorp",
    "Hindalco Industries",
    "Hindustan Unilever",
    "ICICI Bank",
    "Indian Oil Corporation",
    "IndusInd Bank",
    "ITC",
    "JSW Steel",
    "Larsen & Toubro",
    "Mahindra & Mahindra",
    "Maruti Suzuki India",
    "NTPC",
    "Oil & Natural Gas Corporation",
    "Power Grid Corporation of India",
    "State Bank of India",
    "SBI Life Insurance Company",
    "Shree Cement",
    "Sun Pharmaceutical Industries",
    "Tata Consultancy Services",
    "Tata Consumer Products",
    "Tata Motors",
    "Tata Steel",
    "Tech Mahindra",
    "Titan Company",
    "UltraTech Cement",
    "Wipro",
    "Aegis Logistics",
    "Colgate Palmolive",

    "ACC",
    "Adani Enterprises",
    "Adani Green Energy",
    "Ambuja Cements",
    "Apollo Hospitals Enterprise",
    "Avenue Supermarts",
    "Axis Bank",
    "Bajaj Auto",
    "Bajaj Finserv",
    "Bajaj Holdings & Investment",
    "Bandhan Bank",
    "Bank of Baroda",
    "Berger Paints India",
    "Biocon",
    "Bosch",
    "Britannia Industries",
    "Canara Bank",
    "Cipla",
    "Colgate-Palmolive (India)",
    "Container Corporation of India",
    "Cummins India",
    "Dabur India",
    "Divi's Laboratories",
    "Dr. Reddy's Laboratories",
    "Eicher Motors",
    "GAIL",
    "Glenmark Pharmaceuticals",
    "Godrej Consumer Products",
    "Havells India",
    "HCL Technologies",
    "HDFC Asset Management Company",
    "HDFC Bank",
    "HDFC Life Insurance Company",
    "Hindalco Industries",
    "Hindustan Petroleum Corporation",
    "ICICI Bank",
    "IDBI Bank",
    "Indian Oil Corporation",
    "Indraprastha Gas",
    "IndusInd Bank",
    "Infosys",
    "InterGlobe Aviation",
    "JSW Steel",
    "Kotak Mahindra Bank",
    "L&T Finance Holdings",
    "Larsen & Toubro",
    "Laurus Labs",
    "Mahindra & Mahindra Financial Services",
    "Mahindra & Mahindra",
    "MRF",
    "Muthoot Finance",
    "Narayana Hrudayalaya",
    "National Aluminium Company",
    "Navin Fluorine International",
    "Nestlé India",
    "Nippon Life India Asset Management",
    "Petronet LNG",
    "Pfizer",
    "Piramal Enterprises",
    "Pidilite Industries",
    "Power Finance Corporation",
    "Power Grid Corporation of India",
    "RBL Bank",
    "SBI Cards and Payment Services",
    "SBI Life Insurance Company",
    "Shree Cement",
    "Siemens",
    "Sun Pharmaceutical Industries",
    "Sun TV Network",
    "Tata Consumer Products",
    "Tata Motors",
    "Tata Steel",
    "Tata Consultancy Services",
    "Tech Mahindra",
    "Torrent Pharmaceuticals",
    "TVS Motor Company",
    "UltraTech Cement",
    "Vedanta",
    "Vodafone Idea",
    "Suryoday Small Finance Bank",
    "Voltas",
    "Wipro",
    "Coffee Day Enterprises",
    "Polycab"
]

company_symbols = [
    "RELIANCE.NS",
    "HDFCBANK.NS",
    "INFY.NS",
    "ADANIPORTS.NS",
    "ASIANPAINT.NS",
    "NESTLEIND.NS",
    "AXISBANK.NS",
    "BAJAJ-AUTO.NS",
    "BAJFINANCE.NS",
    "KOTAKBANK.NS",
    "BAJAJFINSV.NS",
    "BHARTIARTL.NS",
    "BRITANNIA.NS",
    "CIPLA.NS",
    "COALINDIA.NS",
    "DIVISLAB.NS",
    "DRREDDY.NS",
    "EICHERMOT.NS",
    "GRASIM.NS",
    "HCLTECH.NS",
    "HDFCAMC.NS",
    "HDFCLIFE.NS",
    "HEROMOTOCO.NS",
    "HINDALCO.NS",
    "HINDUNILVR.NS",
    "ICICIBANK.NS",
    "IOC.NS",
    "INDUSINDBK.NS",
    "ITC.NS",
    "JSWSTEEL.NS",
    "LT.NS",
    "M&M.NS",
    "MARUTI.NS",
    "NTPC.NS",
    "ONGC.NS",
    "POWERGRID.NS",
    "SBIN.NS",
    "SBILIFE.NS",
    "SHREECEM.NS",
    "SUNPHARMA.NS",
    "TCS.NS",
    "TATACONSUM.NS",
    "TATAMOTORS.NS",
    "TATASTEEL.NS",
    "TECHM.NS",
    "TITAN.NS",
    "ULTRACEMCO.NS",
    "WIPRO.NS",
    "AEGISCHEM.NS",
    "COLPAL.NS",


    "ACC.NS",
    "ADANIENT.NS",
    "ADANIGREEN.NS",
    "AMBUJACEM.NS",
    "APOLLOHOSP.NS",
    "DMART.NS",
    "AXISBANK.NS",
    "BAJAJ-AUTO.NS",
    "BAJAJFINSV.NS",
    "BAJAJHLDNG.NS",
    "BANDHANBNK.NS",
    "BANKBARODA.NS",
    "BERGEPAINT.NS",
    "BIOCON.NS",
    "BOSCHLTD.NS",
    "BRITANNIA.NS",
    "CANBK.NS",
    "CIPLA.NS",
    "COLPAL.NS",
    "CONCOR.NS",
    "CUMMINSIND.NS",
    "DABUR.NS",
    "DIVISLAB.NS",
    "DRREDDY.NS",
    "EICHERMOT.NS",
    "GAIL.NS",
    "GLENMARK.NS",
    "GODREJCP.NS",
    "HAVELLS.NS",
    "HCLTECH.NS",
    "HDFCAMC.NS",
    "HDFCBANK.NS",
    "HDFCLIFE.NS",
    "HINDALCO.NS",
    "HINDPETRO.NS",
    "ICICIBANK.NS",
    "IDBI.NS",
    "IOC.NS",
    "IGL.NS",
    "INDUSINDBK.NS",
    "INFY.NS",
    "INDIGO.NS",
    "JSWSTEEL.NS",
    "KOTAKBANK.NS",
    "L&TFH.NS",
    "LT.NS",
    "LAURUSLABS.NS",
    "M&MFIN.NS",
    "M&M.NS",
    "MRF.NS",
    "MUTHOOTFIN.NS",
    "NH.NS",
    "NATIONALUM.NS",
    "NAVNETEDUL.NS",
    "NESTLEIND.NS",
    "NAM-INDIA.NS",
    "PETRONET.NS",
    "PFIZER.NS",
    "PEL.NS",
    "PIDILITIND.NS",
    "PFC.NS",
    "POWERGRID.NS",
    "RBLBANK.NS",
    "SBICARD.NS",
    "SBILIFE.NS",
    "SHREECEM.NS",
    "SIEMENS.NS",
    "SUNPHARMA.NS",
    "SUNTV.NS",
    "TATACONSUM.NS",
    "TATAMOTORS.NS",
    "TATASTEEL.NS",
    "TCS.NS",
    "TECHM.NS",
    "TORNTPHARM.NS",
    "TVSMOTOR.NS",
    "ULTRACEMCO.NS",
    "VEDL.NS",
    "IDEA.NS",
    "SURYODAY.NS",
    "VOLTAS.NS",
    "WIPRO.NS",
    "COFFEEDAY.NS",
    "POLYCAB.NS"
]
price=0
repeated=[]
list_of_symbols=[]
for i in range(0,150):
    if(company_symbols[i] not in list_of_symbols):
        list_of_symbols.append(company_symbols[i])
        values=(company_names[i], price, company_symbols[i])
        cur.execute("insert into stocks values(%s,%s,%s)",values)
        db.commit()
    else:
        repeated.append(company_symbols[i])

print()
print(repeated)
print()